# Generated by Django 4.2.6 on 2023-10-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('food_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
